### ISSUE TITLE
support server side encryption (sse) instead of hardcoding aes256

### ISSUE THREAD

**Issue by ianhuynh** [mapbox/mapbox-tile-copy#103]
https://github.com/mapbox/mapbox-tile-copy/blob/master/lib/tilelivecopy.js  hardcoded AES256 as the encryption algorithm.   AWS now supports aws-kms as server side encryption (sse).

the proposal is to pass the encryption algo as a property in  the options object
```
function tilelivecopy(srcUri, s3url, options, callback) {

//  options.sse   : this defaults to aes256 if not set, otherwise, acceptable param could be aws-kms
 
```
Our team can submit PR

**Comment by mapsam** [comment]
Hey @ianhuynh - will gladly accept a PR with an optional parameter and tests! Let me know if I can help. Couple questions (since I'm not too familiar with these options):

1. Is `aws:kms` the only other viable option?
1. Since this will be put into effect via tilelive-s3, do we need to enable [`sseKmsId`](https://github.com/mapbox/tilelive-s3/blob/08e7b4ea175c9245d2b7953a65f8b71c248be4c6/lib/index.js#L73) as an option as well?

**Comment by lefrog** [comment]
Hi @mapsam,
I created a PR for it.
https://github.com/mapbox/mapbox-tile-copy/pull/108
to answer your questions to Ian
1. as of today, there is only 2 possible encryption: AES256 | aws:kms, (look for ServerSideEncryption in http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property)
2. it's just a matter of adding proper query parameter with the tilelive url. For example
`s3://my-s3-bucket/my-tile-key/{z}/{x}/{y}?sse=aws:kms&sseKmsId=my-arn-key-id`

I add a test case for it the PR but really to test it need a valid AWS KMS key which is not something you want to make publically available in the code...

**Comment by springmeyer** [comment]
landed in https://github.com/mapbox/mapbox-tile-copy/pull/108
