### ISSUE TITLE
question on "updating" tiles

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-tile-copy#122]
Hi there,

QQ: I would like to run this more than once, but noticed it just copies the tiles (which given the name is no real surprise :-) )

But if the new mbtiles have removed some tiles, obviously the old ones would still persist in S3. Do you have any suggestions on how best to deal with this?

I could use mbutil to first create tiles locally and then use "aws s3 sync --delete", but that means using a deprecated mbutil.

I could also copy it to a different/new folder on s3 and then use "aws s3 mv --recursive" but that seems like a bad idea.

Finally, I could copy updates to completely new buckets, and put a cloudfront in front of it all and update which bucket it uses...

Any recommendations?

(ps. I could also just spin up actual tileservers rather than using s3, but then I'd have to maintain those and create multiple servers etc etc, which i was hoping to avoid)

**Comment by mapsam** [comment]
Hi @jliebrand - thanks for the question! Knowing where your tiles are, and if they are updated, is outside the scope of this library (and the vector tile specification, which this adheres to). That said, you're on the right track with moving everything to a new s3 prefix (not saying this is the only way). I'd suggest having some sort of intermediate service in the API request that _knows_ where your tilest lives on s3. The HTTP request remains the same but your API internals GET from an updated s3 prefix. 

**So for example (this has a lot of assumptions):**

Let's say you have a tileset called `neat-tileset`. The first time you copy tiles to s3 you run the following command you could add a customized prefix to the s3 location, like `v1`:

```
mapbox-tile-copy neat-data.geojson s3://bucket/neat-tileset/v1/{z}/{x}/{y}
```

So when you request a tile through your API with the following URL

```
https://api.example.com/neat-tileset/0/0/0.mvt
```

Your API would see that request and have some sort of knowledge of where on S3 the `neat-tileset` tiles live. Let's say it's a `TILESET_PREFIX` variable set to `v1`. You're able to get the tile from that s3 bucket/prefix and return it. 

Then you make a change to the source data and update `neat-tileset`. You may go to `v2` and use the following command:

```
mapbox-tile-copy neat-data.geojson s3://bucket/neat-tileset/v2/{z}/{x}/{y}
```

At this point, the last big change you'll have to do is update your `TILESET_PREFIX` to be set to `v2` so you're grabbing tiles from the new location.

**Drawbacks?**

Certainly. Depending on the API that is built and service you are using you'll want to figure out how to set expire tags and content headers so any sort of cache will notice this being a new request and not an old v1 request. Storage costs can become a factor if you do this at scale, and determining where `TILESET_PREFIX` lives and how it is updated can be challenging. But I'll leave those decisions to you :) 

---

Going to close this since as I mentioned before, the feature is out of scope of this library.
